{"name": "test_create_customer_fail_for_existing_email", "status": "passed", "description": "\n        Test case to verify that creating a customer with an existing email fails with the correct error message.\n    ", "start": 1742568684829, "stop": 1742568685617, "uuid": "44f75991-4b5a-41db-8440-a99b30b50315", "historyId": "6e6c37f740cc0c9648f9357c5ab5ad0e", "testCaseId": "8ec61db253740e80f15dab1dff91cce8", "fullName": "ssqatest.tests.backend.customers.test_create_customers_smoke#test_create_customer_fail_for_existing_email", "labels": [{"name": "tag", "value": "tcid47"}, {"name": "tag", "value": "ecombe6"}, {"name": "tag", "value": "customers"}, {"name": "parentSuite", "value": "ssqatest.tests.backend.customers"}, {"name": "suite", "value": "test_create_customers_smoke"}, {"name": "host", "value": "latha"}, {"name": "thread", "value": "15964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ssqatest.tests.backend.customers.test_create_customers_smoke"}]}